version: '3.8'

services:
  # Serviço do PostgreSQL (já existente)
  postgres:
    image: postgres:15-alpine
    container_name: jus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jus_scraper
      POSTGRES_USER: jus_user
      POSTGRES_PASSWORD: jus_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jus_user -d jus_scraper"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: jus-api-backend
    restart: unless-stopped
    ports:
      - "3000:3000" # Mapeia a porta 3000
    environment:
      # Variáveis de ambiente para a API que se conectam ao banco de dados Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jus_scraper
      DB_USER: jus_user
      DB_PASSWORD: jus_password
      JWT_SECRET: jwt_secret_juscash_api_02
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: