version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jus_scraper
      POSTGRES_USER: jus_user
      POSTGRES_PASSWORD: jus_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jus_user -d jus_scraper"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: